# Generated by Django 5.2.5 on 2025-08-29 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vechile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60, null=True, verbose_name='Area Name')),
                ('rating', models.PositiveIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='AreaMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(10, 'Manager'), (20, 'Worker')])),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='parking.companyarea')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingRatePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_space', models.PositiveIntegerField(default=0)),
                ('price', models.PositiveIntegerField(default=0)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='parking.companyarea')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='company.company')),
                ('vechile', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='parking.vechile')),
            ],
        ),
        migrations.CreateModel(
            name='Bookparking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vechile_number', models.CharField(blank=True, max_length=50, null=True)),
                ('per_hour_price', models.PositiveIntegerField(default=0)),
                ('time_in', models.DateTimeField(blank=True, null=True)),
                ('time_out', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(10, 'Book'), (20, 'Parking_In'), (30, 'Parking_Out'), (40, 'Cancel'), (50, 'Completed')], default=10)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('discount_amount', models.FloatField(blank=True, null=True)),
                ('total_amount', models.FloatField(blank=True, null=True)),
                ('is_promocode_used', models.BooleanField(default=False)),
                ('promocode', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='parking.companyarea')),
                ('vechile', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='parking.vechile')),
            ],
        ),
    ]
