# Generated by Django 5.2.5 on 2025-08-29 09:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='areamembership',
            unique_together={('user', 'area')},
        ),
    ]
