# Generated by Django 5.2.5 on 2025-09-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_alter_areamembership_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookparking',
            name='payment_status',
            field=models.IntegerField(choices=[(50, 'None'), (10, 'Initial'), (20, 'Success'), (30, 'Failed'), (40, 'User canceled')], default=50),
        ),
        migrations.AddField(
            model_name='bookparking',
            name='payment_type',
            field=models.IntegerField(choices=[(10, 'CASH'), (20, 'KHALTI'), (30, 'ESWEA')], default=10),
        ),
        migrations.AddField(
            model_name='bookparking',
            name='pidx',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bookparking',
            name='txn_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parkingrateplan',
            name='remaining_space',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
