# Generated by Django 5.2.5 on 2025-09-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_bookparking_payment_status_bookparking_payment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookparking',
            name='total_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
