# Generated by Django 5.2.5 on 2025-09-21 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parking', '0003_bookparking_payment_status_bookparking_payment_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=6, unique=True)),
                ('to_use', models.PositiveIntegerField(default=10)),
                ('remaining_to_use', models.PositiveIntegerField(default=0)),
                ('discount', models.FloatField(default=0)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking.companyarea')),
            ],
        ),
    ]
