# Generated by Django 5.2.5 on 2025-08-29 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_kyc_verified', models.BooleanField(default=False)),
                ('otp', models.IntegerField(blank=True, null=True)),
                ('citizenship_number', models.CharField(blank=True, null=True)),
                ('citizenship_image', models.ImageField(blank=True, null=True, upload_to='citizenship')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='userdetail', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
